// Generated by https://quicktype.io

export interface PokemonListResponse {
    count: number;
    next: string;
    previous: string;
    results: PokemonResponse[];
}

export interface PokemonResponse {
    name: string;
    url: string;
}
